package com.backend.CreativityMarket.AuditLog;

public enum AuditAction {
    CREATE_CASE,
    ASSIGN_CASE,
    UPDATE_CASE,
    RESOLVE_CASE,
    DISMISS_CASE,
    CREATE_BOUNTY,
    UPDATE_BOUNTY,
    DELETE_BOUNTY,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    CREATE_ASSET,
    UPDATE_ASSET,
    DELETE_ASSET,
    UPDATE_USER,
    BAN_USER,
    UNBAN_USER,
    SUSPEND_USER,
    UNSUSPEND_USER,
    PROMOTE_USER_TO_MODERATOR,
    DELETE_USER
}
